project:
  type: website

website:
  title: "Francisco Vargas"
  navbar:
    title: "Francisco Vargas"
    left: 
      - href: Resume_Francisco_Vargas.pdf
        text: "CV"
        target: _blank
    right: 
      - href: projects/index.qmd
    tools:
      - icon: github
        text: GitHub
        href: https://github.com/franc-vargas
      - icon: linkedin
        text: LinkedIn
        href: https://www.linkedin.com/in/francisco-vargas-vega/

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



